<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Juan Manuel Bayona Pacheco">
<meta name="dcterms.date" content="2026-03-13">

<title>Taller 3 — Economías de Aglomeración</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="taller_3_revised_files/libs/clipboard/clipboard.min.js"></script>
<script src="taller_3_revised_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="taller_3_revised_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="taller_3_revised_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="taller_3_revised_files/libs/quarto-html/popper.min.js"></script>
<script src="taller_3_revised_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="taller_3_revised_files/libs/quarto-html/anchor.min.js"></script>
<link href="taller_3_revised_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="taller_3_revised_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="taller_3_revised_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="taller_3_revised_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="taller_3_revised_files/libs/bootstrap/bootstrap-4d7f0bce1131f3e5f9547cd857cfbfc8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#taller-3-de-econometría-espacial" id="toc-taller-3-de-econometría-espacial" class="nav-link active" data-scroll-target="#taller-3-de-econometría-espacial">Taller 3 de Econometría Espacial</a></li>
  <li><a href="#realice-el-mapa-de-densidad-y-distribución-de-puntos-de-las-empresas-del-sector-seleccionado.-interprete-los-resultados-en-términos-de-la-localización-de-las-mayores-densidades.-indague-sobre-el-contexto-de-esta-industria-en-cali-para-dar-una-explicación-con-sentido-económico." id="toc-realice-el-mapa-de-densidad-y-distribución-de-puntos-de-las-empresas-del-sector-seleccionado.-interprete-los-resultados-en-términos-de-la-localización-de-las-mayores-densidades.-indague-sobre-el-contexto-de-esta-industria-en-cali-para-dar-una-explicación-con-sentido-económico." class="nav-link" data-scroll-target="#realice-el-mapa-de-densidad-y-distribución-de-puntos-de-las-empresas-del-sector-seleccionado.-interprete-los-resultados-en-términos-de-la-localización-de-las-mayores-densidades.-indague-sobre-el-contexto-de-esta-industria-en-cali-para-dar-una-explicación-con-sentido-económico.">1. Realice el mapa de densidad y distribución de puntos de las empresas del sector seleccionado. Interprete los resultados en términos de la localización de las mayores densidades. Indague sobre el contexto de esta industria en Cali para dar una explicación con sentido económico.</a></li>
  <li><a href="#calcule-los-siguientes-índices-de-concentración-e-interprételos-con-sentido-económico-dado-el-contexto-de-la-ciudad." id="toc-calcule-los-siguientes-índices-de-concentración-e-interprételos-con-sentido-económico-dado-el-contexto-de-la-ciudad." class="nav-link" data-scroll-target="#calcule-los-siguientes-índices-de-concentración-e-interprételos-con-sentido-económico-dado-el-contexto-de-la-ciudad.">2. Calcule los siguientes índices de concentración e interprételos con sentido económico dado el contexto de la ciudad.</a>
  <ul class="collapse">
  <li><a href="#a-índice-de-herfindahl-hirschman-ihh" id="toc-a-índice-de-herfindahl-hirschman-ihh" class="nav-link" data-scroll-target="#a-índice-de-herfindahl-hirschman-ihh">a) Índice de Herfindahl-Hirschman (IHH)</a></li>
  <li><a href="#b-índice-de-ellison-y-glaeser-1997" id="toc-b-índice-de-ellison-y-glaeser-1997" class="nav-link" data-scroll-target="#b-índice-de-ellison-y-glaeser-1997">b) Índice de Ellison y Glaeser (1997)</a></li>
  <li><a href="#c-índice-de-maurel-y-sédillot-1999" id="toc-c-índice-de-maurel-y-sédillot-1999" class="nav-link" data-scroll-target="#c-índice-de-maurel-y-sédillot-1999">c) Índice de Maurel y Sédillot (1999)</a></li>
  <li><a href="#d-cociente-de-localización-lq-e-índice-de-aislamiento-iq" id="toc-d-cociente-de-localización-lq-e-índice-de-aislamiento-iq" class="nav-link" data-scroll-target="#d-cociente-de-localización-lq-e-índice-de-aislamiento-iq">d) Cociente de Localización (LQ) e Índice de Aislamiento (IQ)</a></li>
  </ul></li>
  <li><a href="#haga-el-mapa-del-lq-e-interprete." id="toc-haga-el-mapa-del-lq-e-interprete." class="nav-link" data-scroll-target="#haga-el-mapa-del-lq-e-interprete.">3. Haga el mapa del LQ e interprete.</a></li>
  <li><a href="#estime-las-funciones-hatk_d-de-duranton-y-overman-2005-y-m-de-marcon-y-puech-2010.-interprete-los-resultados-en-términos-de-la-localización-de-las-mayores-densidades-y-de-la-distancia-a-la-que-se-encuentran-las-empresas." id="toc-estime-las-funciones-hatk_d-de-duranton-y-overman-2005-y-m-de-marcon-y-puech-2010.-interprete-los-resultados-en-términos-de-la-localización-de-las-mayores-densidades-y-de-la-distancia-a-la-que-se-encuentran-las-empresas." class="nav-link" data-scroll-target="#estime-las-funciones-hatk_d-de-duranton-y-overman-2005-y-m-de-marcon-y-puech-2010.-interprete-los-resultados-en-términos-de-la-localización-de-las-mayores-densidades-y-de-la-distancia-a-la-que-se-encuentran-las-empresas.">4. Estime las funciones <span class="math inline">\(\hat{K}_d\)</span> de Duranton y Overman (2005) y <span class="math inline">\(M\)</span> de Marcon y Puech (2010). Interprete los resultados en términos de la localización de las mayores densidades y de la distancia a la que se encuentran las empresas.</a>
  <ul class="collapse">
  <li><a href="#a-función-hatk_d-de-duranton-y-overman-2005" id="toc-a-función-hatk_d-de-duranton-y-overman-2005" class="nav-link" data-scroll-target="#a-función-hatk_d-de-duranton-y-overman-2005">a) Función <span class="math inline">\(\hat{K}_d\)</span> de Duranton y Overman (2005)</a></li>
  <li><a href="#b-función-m-de-marcon-y-puech-2010" id="toc-b-función-m-de-marcon-y-puech-2010" class="nav-link" data-scroll-target="#b-función-m-de-marcon-y-puech-2010">b) Función <span class="math inline">\(M\)</span> de Marcon y Puech (2010)</a></li>
  <li><a href="#referencias" id="toc-referencias" class="nav-link" data-scroll-target="#referencias">Referencias</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Taller 3 — Economías de Aglomeración</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Juan Manuel Bayona Pacheco </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2026-03-13</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="taller-3-de-econometría-espacial" class="level2">
<h2 class="anchored" data-anchor-id="taller-3-de-econometría-espacial">Taller 3 de Econometría Espacial</h2>
</section>
<section id="realice-el-mapa-de-densidad-y-distribución-de-puntos-de-las-empresas-del-sector-seleccionado.-interprete-los-resultados-en-términos-de-la-localización-de-las-mayores-densidades.-indague-sobre-el-contexto-de-esta-industria-en-cali-para-dar-una-explicación-con-sentido-económico." class="level1">
<h1>1. Realice el mapa de densidad y distribución de puntos de las empresas del sector seleccionado. Interprete los resultados en términos de la localización de las mayores densidades. Indague sobre el contexto de esta industria en Cali para dar una explicación con sentido económico.</h1>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 6. Mapa de distribución de puntos del sector ─────────────────────────────</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> barriosCali,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>          <span class="fu">aes</span>(<span class="at">fill =</span> <span class="st">"Barrio"</span>),</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">color =</span> <span class="st">"grey50"</span>, <span class="at">linewidth =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Barrio"</span> <span class="ot">=</span> <span class="st">"grey95"</span>),</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>                    <span class="at">name   =</span> <span class="st">""</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>                    <span class="at">guide  =</span> <span class="fu">guide_legend</span>(</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>                      <span class="at">order        =</span> <span class="dv">1</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>                      <span class="at">keywidth     =</span> <span class="fu">unit</span>(<span class="fl">0.3</span>, <span class="st">"cm"</span>),</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>                      <span class="at">keyheight    =</span> <span class="fu">unit</span>(<span class="fl">0.3</span>, <span class="st">"cm"</span>),</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>                      <span class="at">override.aes =</span> <span class="fu">list</span>(<span class="at">alpha =</span> <span class="fl">0.1</span>),</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>                      <span class="at">label.theme  =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">6</span>))) <span class="sc">+</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> points, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="fl">0.20</span>, <span class="at">alpha =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position  =</span> <span class="fu">c</span>(<span class="fl">0.2</span>, <span class="fl">0.2</span>),</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.title     =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>),</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.spacing.y =</span> <span class="fu">unit</span>(<span class="sc">-</span><span class="fl">0.3</span>, <span class="st">"cm"</span>)) <span class="co">#+</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="taller_3_revised_files/figure-html/distribucion-1.png" class="img-fluid figure-img" width="384"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>  <span class="co">#canvas(3, 5, units = "in")</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 7. Mapa de densidad kernel bidimensional del sector ──────────────────────</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> barriosCali,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>          <span class="fu">aes</span>(<span class="at">fill =</span> <span class="st">"Barrio"</span>),</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">color =</span> <span class="st">"grey50"</span>, <span class="at">linewidth =</span> <span class="fl">0.25</span>) <span class="sc">+</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Barrio"</span> <span class="ot">=</span> <span class="st">"grey95"</span>),</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>                    <span class="at">name   =</span> <span class="st">""</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>                    <span class="at">guide  =</span> <span class="fu">guide_legend</span>(</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>                      <span class="at">order        =</span> <span class="dv">1</span>,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>                      <span class="at">keywidth     =</span> <span class="fu">unit</span>(<span class="fl">0.3</span>, <span class="st">"cm"</span>),</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>                      <span class="at">keyheight    =</span> <span class="fu">unit</span>(<span class="fl">0.3</span>, <span class="st">"cm"</span>),</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>                      <span class="at">override.aes =</span> <span class="fu">list</span>(<span class="at">alpha =</span> <span class="fl">0.1</span>),</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>                      <span class="at">label.theme  =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">6</span>))) <span class="sc">+</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> points, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="fl">0.20</span>, <span class="at">alpha =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">new_scale_fill</span>() <span class="sc">+</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_density_2d</span>(<span class="at">data =</span> data,</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">fill =</span> <span class="fu">after_stat</span>(level)),</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>                  <span class="at">geom       =</span> <span class="st">"polygon"</span>,   <span class="co"># Áreas rellenas por nivel de densidad</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>                  <span class="at">alpha      =</span> <span class="fl">0.4</span>,</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>                  <span class="at">color      =</span> <span class="cn">NA</span>,          <span class="co"># Sin borde entre niveles</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>                  <span class="at">show.legend =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">option =</span> <span class="st">"viridis"</span>,</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>                       <span class="at">breaks =</span> <span class="cf">function</span>(x) <span class="fu">range</span>(x),</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>                       <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Mín"</span>, <span class="st">"Máx"</span>),</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>                       <span class="at">name   =</span> <span class="st">"Densidad"</span>,</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>                       <span class="at">guide  =</span> <span class="fu">guide_colorbar</span>(</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>                         <span class="at">order        =</span> <span class="dv">1</span>,</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>                         <span class="at">barwidth     =</span> <span class="fu">unit</span>(<span class="fl">0.3</span>, <span class="st">"cm"</span>),</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>                         <span class="at">barheight    =</span> <span class="fu">unit</span>(<span class="fl">0.5</span>, <span class="st">"cm"</span>),</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>                         <span class="at">title.theme  =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">6</span>),</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>                         <span class="at">label.theme  =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">6</span>))) <span class="sc">+</span></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position  =</span> <span class="fu">c</span>(<span class="fl">0.2</span>, <span class="fl">0.2</span>),</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.title     =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>),</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.spacing.y =</span> <span class="fu">unit</span>(<span class="sc">-</span><span class="fl">0.3</span>, <span class="st">"cm"</span>)) <span class="co">#+</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="taller_3_revised_files/figure-html/densidad-1.png" class="img-fluid figure-img" width="384"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>  <span class="co">#canvas(3, 5, units = "in")</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Los mapas de distribución espacial y densidad sugieren una concentración de empresas dedicadas a la fabricación de partes y piezas de carpintería para edificios y construcción en la zona norte-central de Cali. Esta aglomeración puede explicarse por la presencia de economías de aglomeración asociadas al sector de la construcción. Históricamente, el centro de la ciudad ha concentrado proveedores de insumos, ferreterías y comercios mayoristas de materiales de construcción, lo que facilita los encadenamientos productivos y reduce los costos logísticos de las empresas. Asimismo, al tratarse de insumos intermedios para este sector productivo, la localización central permite un acceso más directo a la demanda proveniente de proyectos de construcción y remodelación, generando beneficios de información asociados a la concentración de trabajadores especializados en un espacio próximo.</p>
</section>
<section id="calcule-los-siguientes-índices-de-concentración-e-interprételos-con-sentido-económico-dado-el-contexto-de-la-ciudad." class="level1">
<h1>2. Calcule los siguientes índices de concentración e interprételos con sentido económico dado el contexto de la ciudad.</h1>
<section id="a-índice-de-herfindahl-hirschman-ihh" class="level3">
<h3 class="anchored" data-anchor-id="a-índice-de-herfindahl-hirschman-ihh">a) Índice de Herfindahl-Hirschman (IHH)</h3>
<p>El <strong>Índice de Herfindahl-Hirschman (IHH)</strong> mide el grado de concentración de una actividad económica en un conjunto de unidades geográficas(Herfindahl, 1950; Hirschman, 1945). En este contexto, permite evaluar qué tan concentradas están las empresas del sector en los distintos barrios de Cali. Matemáticamente se define como:</p>
<p><span class="math display">\[HHI = \sum_{i=1}^{N} s_i^2\]</span></p>
<p>donde <span class="math inline">\(s_i\)</span> es la participación del barrio <span class="math inline">\(i\)</span> en el total de empresas del sector, y <span class="math inline">\(N\)</span> es el número de barrios con al menos una empresa del sector.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 1. Intersección espacial: asignar cada empresa del sector a su barrio ────</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>empresas_sector_barrio <span class="ot">&lt;-</span> <span class="fu">st_join</span>(points, barriosCali)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 1.1 Verificación del sector en el objeto espacial</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co">#unique(empresas_sector_barrio$ciiu_4)</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 2. Conteo de empresas del sector por barrio ──────────────────────────────</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>empresas_barrio <span class="ot">&lt;-</span> empresas_sector_barrio <span class="sc">|&gt;</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span>        <span class="co"># Elimina geometría para operar como tabla</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(barrio) <span class="sc">|&gt;</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">empresas =</span> <span class="fu">n</span>())    <span class="co"># n() cuenta observaciones por grupo</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 3. Total de empresas del sector en Cali ──────────────────────────────────</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>Total_empresas <span class="ot">&lt;-</span> empresas_barrio <span class="sc">|&gt;</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">tot_empresas =</span> <span class="fu">sum</span>(empresas))</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 4. Total de empresas de la economía general en Cali ──────────────────────</span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>empresas_cali <span class="ot">&lt;-</span> data_total <span class="sc">|&gt;</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">n =</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_empresas_cali =</span> <span class="fu">sum</span>(n))</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a><span class="co"># 4.1 Participación del sector en la economía general (%)</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>participacion_sector_actividad <span class="ot">&lt;-</span> (Total_empresas<span class="sc">$</span>tot_empresas <span class="sc">/</span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>                                   empresas_cali<span class="sc">$</span>total_empresas_cali) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Participación del sector: %.2f%%</span><span class="sc">\n</span><span class="st">"</span>, participacion_sector_actividad))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Participación del sector: 4.08%</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 5. Cálculo del IHH ───────────────────────────────────────────────────────</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 5.1 Participación de cada barrio en el total del sector (s_i)</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>empresas_barrio <span class="ot">&lt;-</span> empresas_barrio <span class="sc">|&gt;</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">share =</span> empresas <span class="sc">/</span> <span class="fu">sum</span>(empresas))</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 5.2 Top 4 barrios por participación sectorial</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>empresas_barrio <span class="sc">|&gt;</span> <span class="fu">slice_max</span>(share, <span class="at">n =</span> <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  barrio                empresas  share
  &lt;chr&gt;                    &lt;int&gt;  &lt;dbl&gt;
1 UNION DE VDA. POPULAR       13 0.0657
2 SAN NICOLAS                 11 0.0556
3 EL RODEO                     9 0.0455
4 EL TRONCAL                   8 0.0404</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 5.3 IHH = suma de participaciones al cuadrado</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>HHI <span class="ot">&lt;-</span> <span class="fu">sum</span>(empresas_barrio<span class="sc">$</span>share<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"HHI:"</span>, <span class="fu">round</span>(HHI, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>HHI: 0.0212 </code></pre>
</div>
</div>
<p>Como contexto del sector, existen un total de 198 empresas repartidas en los barrios de Cali dedicadas a la fabricación de partes y piezas de carpintería para construcción, representando apenas el 4.07% de la actividad económica de la ciudad. Los barrios con mayor participación del sector son Unión de Vda. Popular, San Nicolás, El Rodeo y El Troncal, concentrando cada uno aproximadamente el 6.5% de las empresas del sector.</p>
<p>El IHH sugiere que la actividad se encuentra distribuida entre varios barrios y no concentrada en uno o pocos de ellos. Este resultado contrasta con la concentración visual observada en el mapa de densidad, lo que puede atribuirse a dos sesgos estructurales del estimador: primero, el <strong>sesgo de tamaño y aglomeración</strong>, donde la concentración de toda la economía en un barrio puede inflar la participación del sector sin que ello refleje especialización sectorial propia; segundo, el <strong>sesgo de unidad espacial</strong> (<em>MAUP</em>), dado que el IHH trata cada barrio como una unidad independiente sin considerar la dependencia espacial entre barrios contiguos. Los índices siguientes buscan corregir cada uno de estos sesgos progresivamente.</p>
</section>
<section id="b-índice-de-ellison-y-glaeser-1997" class="level3">
<h3 class="anchored" data-anchor-id="b-índice-de-ellison-y-glaeser-1997">b) Índice de Ellison y Glaeser (1997)</h3>
<p>El <strong>Índice de Ellison y Glaeser (EG)</strong> mide el grado de aglomeración espacial de una industria corrigiendo dos sesgos del IHH: (1) la concentración general de la actividad económica en la ciudad, y (2) el tamaño relativo de las empresas dentro del sector (Ellison y Glaeser, 1997). El índice se define como:</p>
<p><span class="math display">\[\hat{\gamma}_{EG} = \frac{G_{EG}}{(1-\sum_{i=1}^{N} x_i^2)(1-H)} - \frac{H}{1-H}\]</span></p>
<p>donde:</p>
<p><span class="math display">\[G_{EG} = \sum_{i=1}^{N}(s_i - x_i)^2 \qquad H = \sum_{j=1}^{J} z_j^2\]</span></p>
<ul>
<li><span class="math inline">\(s_i\)</span> = participación del sector en el barrio <span class="math inline">\(i\)</span></li>
<li><span class="math inline">\(x_i\)</span> = participación de todas las empresas de la ciudad en el barrio <span class="math inline">\(i\)</span></li>
<li><span class="math inline">\(H\)</span> = índice de Herfindahl de tamaños de plantas dentro del sector</li>
<li><span class="math inline">\(J\)</span> = número total de empresas del sector</li>
<li><span class="math inline">\(z_j\)</span> = participación del empleo de la empresa <span class="math inline">\(j\)</span> en el empleo total del sector</li>
</ul>
<p>Dado que no se dispone de información sobre el tamaño de las empresas, se asume distribución uniforme: <span class="math inline">\(z_j = 1/J\)</span> para toda <span class="math inline">\(j\)</span>, lo que implica:</p>
<p><span class="math display">\[H = \sum_{j=1}^{J} \left(\frac{1}{J}\right)^2 = \frac{1}{J}\]</span></p>
<p>Para <span class="math inline">\(J\)</span> suficientemente grande (<span class="math inline">\(J \gg 1\)</span>), <span class="math inline">\(H \approx 0\)</span> y el índice se simplifica a:</p>
<p><span class="math display">\[\hat{\gamma}_{EG} \approx \frac{G_{EG}}{1-\sum_{i=1}^{N} x_i^2}\]</span></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 1. Verificación del dataframe de barrios del sector ──────────────────────</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co">#head(empresas_barrio)</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 2. Empresas totales por barrio — solo barrios con presencia del sector ───</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>total_barrio <span class="ot">&lt;-</span> data_total <span class="sc">|&gt;</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(cod_barrio <span class="sc">%in%</span> empresas_sector_barrio<span class="sc">$</span>cod_barrio) <span class="sc">|&gt;</span>  <span class="co"># Barrios con sector</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">|&gt;</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(barrio) <span class="sc">|&gt;</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_empresas =</span> <span class="fu">n</span>())</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co"># 2.1 Participación de la economía general en cada barrio (x_i)</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>total_barrio <span class="ot">&lt;-</span> total_barrio <span class="sc">|&gt;</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">xi =</span> total_empresas <span class="sc">/</span> <span class="fu">sum</span>(total_empresas))</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 3. Total de empresas en barrios con presencia del sector ─────────────────</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>total_empresas_barriosMC <span class="ot">&lt;-</span> total_barrio <span class="sc">|&gt;</span></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">empresas_barrios =</span> <span class="fu">sum</span>(total_empresas))</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a><span class="co"># 3.1 Participación del sector en el conjunto de barrios con presencia sectorial</span></span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>participacion_sector_actividadB <span class="ot">&lt;-</span> Total_empresas<span class="sc">$</span>tot_empresas <span class="sc">/</span></span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>                                   total_empresas_barriosMC<span class="sc">$</span>empresas_barrios</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 4. Construcción del dataframe unificado para el índice ───────────────────</span></span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Une participación del sector (s_i) con participación de la economía (x_i)</span></span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">left_join</span>(empresas_barrio, total_barrio, <span class="at">by =</span> <span class="st">"barrio"</span>) <span class="sc">|&gt;</span></span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">si =</span> <span class="st">"share"</span>)</span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 5. Cálculo de componentes del índice EG ──────────────────────────────────</span></span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a><span class="co"># 5.1 G_EG: distancia L² entre distribución del sector y de la economía</span></span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a>G <span class="ot">&lt;-</span> <span class="fu">sum</span>((df<span class="sc">$</span>si <span class="sc">-</span> df<span class="sc">$</span>xi)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a><span class="co"># 5.2 H: índice de Herfindahl bajo tamaño uniforme (H = 1/J)</span></span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a>H <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> Total_empresas<span class="sc">$</span>tot_empresas</span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a><span class="co"># 5.3 Denominador: (1 - sum(x_i^2)) — Gini-Simpson de la economía de referencia</span></span>
<span id="cb11-36"><a href="#cb11-36" aria-hidden="true" tabindex="-1"></a>sumxi <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">sum</span>(df<span class="sc">$</span>xi<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb11-37"><a href="#cb11-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-38"><a href="#cb11-38" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 6. Estimación del índice gamma_EG ────────────────────────────────────────</span></span>
<span id="cb11-39"><a href="#cb11-39" aria-hidden="true" tabindex="-1"></a>gamma_EG <span class="ot">&lt;-</span> (G <span class="sc">/</span> (sumxi <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> H))) <span class="sc">-</span> (H <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> H))</span>
<span id="cb11-40"><a href="#cb11-40" aria-hidden="true" tabindex="-1"></a><span class="co">#gamma_EG</span></span>
<span id="cb11-41"><a href="#cb11-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-42"><a href="#cb11-42" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 7. Significancia estadística (EG 1997, pie de página 13) ─────────────────</span></span>
<span id="cb11-43"><a href="#cb11-43" aria-hidden="true" tabindex="-1"></a>n_f      <span class="ot">&lt;-</span> Total_empresas<span class="sc">$</span>tot_empresas       <span class="co"># Número de empresas del sector</span></span>
<span id="cb11-44"><a href="#cb11-44" aria-hidden="true" tabindex="-1"></a>sum_xi2  <span class="ot">&lt;-</span> <span class="fu">sum</span>(df<span class="sc">$</span>xi<span class="sc">^</span><span class="dv">2</span>)                      <span class="co"># Suma de x_i^2</span></span>
<span id="cb11-45"><a href="#cb11-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-46"><a href="#cb11-46" aria-hidden="true" tabindex="-1"></a><span class="co"># 7.1 Varianza asintótica del estimador bajo H0</span></span>
<span id="cb11-47"><a href="#cb11-47" aria-hidden="true" tabindex="-1"></a>var_gamma <span class="ot">&lt;-</span> (<span class="dv">2</span> <span class="sc">*</span> sum_xi2) <span class="sc">/</span> ((<span class="dv">1</span> <span class="sc">-</span> H)<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> n_f)</span>
<span id="cb11-48"><a href="#cb11-48" aria-hidden="true" tabindex="-1"></a>se_gamma  <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(var_gamma)</span>
<span id="cb11-49"><a href="#cb11-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-50"><a href="#cb11-50" aria-hidden="true" tabindex="-1"></a><span class="co"># 7.2 Estadístico z y p-value (contraste bilateral)</span></span>
<span id="cb11-51"><a href="#cb11-51" aria-hidden="true" tabindex="-1"></a>z_stat  <span class="ot">&lt;-</span> gamma_EG <span class="sc">/</span> se_gamma</span>
<span id="cb11-52"><a href="#cb11-52" aria-hidden="true" tabindex="-1"></a>p_value <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(z_stat)))</span>
<span id="cb11-53"><a href="#cb11-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-54"><a href="#cb11-54" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"gamma_EG:"</span>, <span class="fu">round</span>(gamma_EG, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>gamma_EG: 0.0119 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"z-stat:  "</span>, <span class="fu">round</span>(z_stat,   <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>z-stat:   0.6176 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"p-value: "</span>, <span class="fu">round</span>(p_value,  <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>p-value:  0.5368 </code></pre>
</div>
</div>
<p>El índice EG corrige el sesgo de concentración total de la economía presente en el IHH. En Cali, los barrios donde existe al menos una empresa del sector poseen alrededor de 2.819 empresas en total, de las cuales el sector de insumos intermedios para construcción representa el <span class="math inline">\(7\%\)</span> de la actividad económica dentro de esos barrios específicos. El p-value obtenido (0.53) es considerablemente mayor que los niveles de significancia convencionales ( <span class="math inline">\(1\%\)</span> , <span class="math inline">\(5\%\)</span>, y <span class="math inline">\(10\%\)</span> ), por lo que no se rechaza la hipótesis nula de ausencia de aglomeración espacial. Esto sugiere que la distribución de co-localización del sector en Cali no es estadísticamente diferente de una distribución aleatoria condicionada a la distribución general de la actividad económica. El estadístico <span class="math inline">\(\hat{\gamma}_{EG} = 0.005\)</span> confirma la ausencia de especialización sectorial en barrios específicos más allá de la especialización que impone la economía general en esas áreas.</p>
</section>
<section id="c-índice-de-maurel-y-sédillot-1999" class="level3">
<h3 class="anchored" data-anchor-id="c-índice-de-maurel-y-sédillot-1999">c) Índice de Maurel y Sédillot (1999)</h3>
<p>El índice de Maurel y Sédillot (MS) es una extensión del EG que refina la definición de probabilidad de co-localización (Maurel y Sédillot, 1999). Mientras EG evalúa la probabilidad de que dos trabajadores del sector se ubiquen en el mismo barrio respecto a dos trabajadores de cualquier sector, MS condiciona exclusivamente sobre pares de trabajadores que pertenecen a <strong>empresas distintas</strong> dentro del sector, eliminando la información de co-localización intra-empresa que EG incluye mecánicamente. Formalmente:</p>
<p><span class="math display">\[\hat{\gamma}_{MS} = \frac{G_{MS}}{(1-\sum_{i=1}^{N} x_i^2)(1-H)} - \frac{H}{1-H}\]</span></p>
<p>donde:</p>
<p><span class="math display">\[G_{MS} = \sum_i (s_i^2 - x_i^2)\]</span></p>
<p>La hipótesis nula de ambos estimadores es la misma: la distribución intrasectorial es indistinguible de la distribución multisectorial a lo largo de Cali.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 1. Cálculo de G_MS ───────────────────────────────────────────────────────</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># G_MS = sum(s_i^2 - x_i^2): diferencia de probabilidades de co-localización</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># entre el sector y la economía general (sin término cruzado)</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>G_MS <span class="ot">&lt;-</span> <span class="fu">sum</span>((df<span class="sc">$</span>si)<span class="sc">^</span><span class="dv">2</span> <span class="sc">-</span> (df<span class="sc">$</span>xi)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 2. Estimación del índice gamma_MS ────────────────────────────────────────</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Reutiliza sumxi = (1 - sum(xi^2)) y H = 1/J del bloque anterior</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>gamma_MS <span class="ot">&lt;-</span> (G_MS <span class="sc">/</span> (sumxi <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> H))) <span class="sc">-</span> (H <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> H))</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"gamma_MS:"</span>, <span class="fu">round</span>(gamma_MS, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>gamma_MS: -0.021 </code></pre>
</div>
</div>
<p><span class="math inline">\(\hat{\gamma}_{MS} = -0.021\)</span> ofrece una visión más conservadora de la aglomeración sectorial. El signo negativo — frente al valor positivo de <span class="math inline">\(\hat{\gamma}_{EG}\)</span> — se explica por la diferente definición de <span class="math inline">\(G\)</span>: MS descarta el término cruzado <span class="math inline">\(2\sum_i s_i x_i\)</span> que EG incluye, de modo que cuando el sector está subrepresentado en los barrios de mayor peso económico (como San Nicolás, con <span class="math inline">\(x_i = 0.1447\)</span> y <span class="math inline">\(LQ = 0.38\)</span>), <span class="math inline">\(G_{MS}\)</span> resulta menor que <span class="math inline">\(G_{EG}\)</span>, generando una estimación de <span class="math inline">\(\gamma\)</span> más baja e incluso negativa. En conjunto, ambos estimadores confirman la misma conclusión: las decisiones de co-localización de las empresas de insumos intermedios para construcción en Cali no obedecen a un proceso de clusterización en barrios específicos, sino que siguen la distribución multisectorial de la actividad económica a lo largo de la ciudad.</p>
</section>
<section id="d-cociente-de-localización-lq-e-índice-de-aislamiento-iq" class="level3">
<h3 class="anchored" data-anchor-id="d-cociente-de-localización-lq-e-índice-de-aislamiento-iq">d) Cociente de Localización (LQ) e Índice de Aislamiento (IQ)</h3>
<p>El <strong>Cociente de Localización</strong> (LQ) mide cuántas empresas del sector existen por empresa de la economía general en el barrio <span class="math inline">\(i\)</span>, relativo al promedio de Cali :</p>
<p><span class="math display">\[LQ_i = \frac{s_i}{x_i} = \frac{e_{si}/E_s}{e_i/E}\]</span></p>
<p>donde <span class="math inline">\(e_{si}\)</span> es el número de empresas del sector en el barrio <span class="math inline">\(i\)</span>, <span class="math inline">\(E_s\)</span> el total del sector en Cali, <span class="math inline">\(e_i\)</span> el total de empresas en el barrio <span class="math inline">\(i\)</span>, y <span class="math inline">\(E\)</span> el total de la economía. Un <span class="math inline">\(LQ_i &gt; 1\)</span> indica especialización relativa del barrio en el sector; <span class="math inline">\(LQ_i &lt; 1\)</span> señala subrepresentación.</p>
<p>El <strong>Índice de Aislamiento</strong> (IQ) pondera el LQ por la participación del sector <span class="math inline">\(s_i\)</span>, produciendo el LQ promedio que enfrenta una empresa típica del sector dado su barrio de localización:</p>
<p><span class="math display">\[IQ = \sum_i s_i \cdot LQ_i = \sum_i \frac{s_i^2}{x_i}\]</span></p>
<p>Un <span class="math inline">\(IQ &gt; 1\)</span> indica que, en promedio, las empresas del sector se localizan en barrios con mayor especialización sectorial que la media de Cali.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 1. Cálculo del LQ por barrio ─────────────────────────────────────────────</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">|&gt;</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">LQ =</span> si <span class="sc">/</span> xi,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">LQ =</span> <span class="fu">ifelse</span>(<span class="fu">is.nan</span>(LQ) <span class="sc">|</span> <span class="fu">is.infinite</span>(LQ), <span class="cn">NA</span>, LQ)  <span class="co"># Excluye divisiones por cero</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 2. Top 10 barrios por LQ ─────────────────────────────────────────────────</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>df <span class="sc">|&gt;</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(LQ)) <span class="sc">|&gt;</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(LQ, <span class="at">n =</span> <span class="dv">10</span>) <span class="sc">|&gt;</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(barrio, empresas, total_empresas, si, xi, LQ)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 6
   barrio                          empresas total_empresas      si      xi    LQ
   &lt;chr&gt;                              &lt;int&gt;          &lt;int&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 EL MORTINAL                            1              1 0.00505 3.55e-4 14.2 
 2 EL PRADO                               2              4 0.0101  1.42e-3  7.12
 3 SECTOR LOS MANGOS (CANAV.NORTE)        1              2 0.00505 7.09e-4  7.12
 4 RODRIGO LARA BONILLA                   4              9 0.0202  3.19e-3  6.33
 5 PRADOS DEL SUR                         1              3 0.00505 1.06e-3  4.75
 6 JOSE M. CORDOBA                        2              7 0.0101  2.48e-3  4.07
 7 EL RODEO                               9             32 0.0455  1.14e-2  4.00
 8 ASPROSOCIAL DIAMANTE                   2              8 0.0101  2.84e-3  3.56
 9 EL REFUGIO                             1              4 0.00505 1.42e-3  3.56
10 JOSE HOLGUIN GARCES                    1              4 0.00505 1.42e-3  3.56
11 LIMONAR - CATAYA                       2              8 0.0101  2.84e-3  3.56
12 PRIMITIVO CRESPO                       4             16 0.0202  5.68e-3  3.56</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 3. Índice de Aislamiento (IQ) ────────────────────────────────────────────</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>IQ <span class="ot">&lt;-</span> <span class="fu">sum</span>(df<span class="sc">$</span>si<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> df<span class="sc">$</span>xi, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"IQ (Índice de Aislamiento):"</span>, <span class="fu">round</span>(IQ, <span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>IQ (Índice de Aislamiento): 1.8837 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 4. Top 10 barrios por participación del sector (s_i) ─────────────────────</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Identifica barrios con mayor peso muestral real — más informativos para el IQ</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>df <span class="sc">|&gt;</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(LQ)) <span class="sc">|&gt;</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(si, <span class="at">n =</span> <span class="dv">10</span>) <span class="sc">|&gt;</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(barrio, empresas, total_empresas, si, xi, LQ)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 6
   barrio                   empresas total_empresas     si      xi    LQ
   &lt;chr&gt;                       &lt;int&gt;          &lt;int&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 UNION DE VDA. POPULAR          13             56 0.0657 0.0199  3.31 
 2 SAN NICOLAS                    11            408 0.0556 0.145   0.384
 3 EL RODEO                        9             32 0.0455 0.0114  4.00 
 4 EL TRONCAL                      8             91 0.0404 0.0323  1.25 
 5 BARRIO OBRERO                   6            112 0.0303 0.0397  0.763
 6 SIN DEFINIR                     6            111 0.0303 0.0394  0.770
 7 CHAPINERO                       5             35 0.0253 0.0124  2.03 
 8 LA FLORESTA                     5             68 0.0253 0.0241  1.05 
 9 JOSE MANUEL MARROQU?N II        4             31 0.0202 0.0110  1.84 
10 PRIMITIVO CRESPO                4             16 0.0202 0.00568 3.56 
11 RODRIGO LARA BONILLA            4              9 0.0202 0.00319 6.33 
12 SAN PASCUAL                     4             26 0.0202 0.00922 2.19 </code></pre>
</div>
</div>
<p>Los resultados muestran que los barrios con mayor <span class="math inline">\(LQ\)</span> son <strong>El Mortinal</strong> (<span class="math inline">\(s_i = 0.0050\)</span>, <span class="math inline">\(x_i = 0.00035\)</span>, <span class="math inline">\(LQ = 14.23\)</span>), <strong>El Prado</strong> (<span class="math inline">\(s_i = 0.0101\)</span>, <span class="math inline">\(x_i = 0.00142\)</span>, <span class="math inline">\(LQ = 7.12\)</span>) y <strong>Sector Los Mangos-Canaverejo Norte</strong> (<span class="math inline">\(s_i = 0.0050\)</span>, <span class="math inline">\(x_i = 0.00071\)</span>, <span class="math inline">\(LQ = 7.12\)</span>), valores que a primera vista sugerirían una especialización sectorial extrema. Sin embargo, estos resultados obedecen a una limitación estructural del índice: cuando la masa económica de referencia <span class="math inline">\(x_i\)</span> es pequeña, cualquier empresa del sector infla mecánicamente el cociente sin reflejar una decisión de aglomeración económicamente significativa. El caso límite es <strong>El Mortinal</strong>, donde una única empresa constructora representa la totalidad de la actividad económica del barrio, generando un <span class="math inline">\(LQ = 14.23\)</span> que constituye un artefacto muestral sin validez estadística. El mismo fenómeno opera en <strong>El Prado</strong> con apenas dos empresas del sector y en <strong>Sector Los Mangos-Canaverejo Norte</strong> con una sola observación — barrios donde la escasez de masa económica hace que el denominador <span class="math inline">\(x_i\)</span> sea suficientemente pequeño como para producir valores extremos.</p>
<p>Para corregir esta limitación, el <span class="math inline">\(IQ = \sum_i s_i^2/x_i\)</span> pondera el <span class="math inline">\(LQ\)</span> por la participación del sector <span class="math inline">\(s_i\)</span>, produciendo el número promedio de empresas del sector que enfrenta una empresa del sector por cada empresa de la economía general en su barrio de localización — es decir, cuántas veces más densa es la presencia sectorial en el vecindario típico de una empresa del sector respecto al vecindario típico de cualquier empresa de la economía. Un valor <span class="math inline">\(IQ = 1.88\)</span> indica que las empresas del sector tienden a localizarse en barrios donde la densidad sectorial es casi el doble del promedio de la ciudad. Los barrios analíticamente relevantes — aquellos que combinan <span class="math inline">\(s_i\)</span> suficiente con especialización genuina — son tres. <strong>El Rodeo</strong> presenta la mayor especialización relativa con soporte muestral razonable: <span class="math inline">\(9\)</span> empresas del sector sobre <span class="math inline">\(32\)</span> totales (<span class="math inline">\(s_i = 0.0455\)</span>, <span class="math inline">\(x_i = 0.0114\)</span>, <span class="math inline">\(LQ = 4.00\)</span>), lo que indica que encontrar una empresa del sector en ese barrio es cuatro veces más probable que en un barrio promedio de Cali. <strong>Unión de Vda. Popular</strong> concentra el mayor peso sectorial absoluto con <span class="math inline">\(13\)</span> empresas (<span class="math inline">\(s_i = 0.0657\)</span>, <span class="math inline">\(x_i = 0.0199\)</span>, <span class="math inline">\(LQ = 3.31\)</span>), sugiriendo especialización genuina respaldada por masa muestral. <strong>San Nicolás</strong>, en contraste, siendo el corredor comercial más importante de Cali al abarcar el <span class="math inline">\(14.47\%\)</span> de toda la actividad empresarial de la ciudad (<span class="math inline">\(x_i = 0.1447\)</span>, <span class="math inline">\(11\)</span> empresas del sector), presenta un <span class="math inline">\(LQ = 0.38\)</span>, resultado consistente con una economía suficientemente diversificada donde ningún sector logra sobre-representarse — su peso en el <span class="math inline">\(IQ\)</span> es alto por <span class="math inline">\(s_i\)</span>, pero su <span class="math inline">\(LQ &lt; 1\)</span> lo excluye como polo de especialización constructora.</p>
</section>
</section>
<section id="haga-el-mapa-del-lq-e-interprete." class="level1">
<h1>3. Haga el mapa del LQ e interprete.</h1>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 1. Unión del LQ al shapefile de barrios ──────────────────────────────────</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>lq_map <span class="ot">&lt;-</span> barriosCali <span class="sc">|&gt;</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename_with</span>(tolower) <span class="sc">|&gt;</span>                          <span class="co"># Estandariza nombres a minúsculas</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(df <span class="sc">|&gt;</span> <span class="fu">select</span>(barrio, LQ), <span class="at">by =</span> <span class="st">"barrio"</span>)  <span class="co"># Agrega LQ por barrio</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 2. Mapa coroplético del LQ ───────────────────────────────────────────────</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(lq_map) <span class="sc">+</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> LQ), <span class="at">color =</span> <span class="st">"grey50"</span>, <span class="at">linewidth =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">option   =</span> <span class="st">"plasma"</span>,</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>                       <span class="at">name     =</span> <span class="st">"LQ"</span>,</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>                       <span class="at">na.value =</span> <span class="st">"grey85"</span>,           <span class="co"># Barrios sin sector en gris</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>                       <span class="at">breaks   =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">5</span>),</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>                       <span class="at">labels   =</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="st">"1 (media)"</span>, <span class="st">"2"</span>, <span class="st">"5+"</span>)) <span class="sc">+</span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title    =</span> <span class="st">"Cociente de Localización por barrio"</span>,</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Sector CIIU 2030 — Cali"</span>,</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption  =</span> <span class="st">"Fuente: DANE, Censo Económico 2005"</span>) <span class="sc">+</span></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="fu">c</span>(<span class="fl">0.2</span>, <span class="fl">0.3</span>)) <span class="co">#+</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="taller_3_revised_files/figure-html/mapa_LQ-1.png" class="img-fluid figure-img" width="384"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>  <span class="co">#canvas(3, 5, units = "in")</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>El mapa cartográfico del LQ revela tres patrones diferenciables. En el área urbana consolidada predominan polígonos de azul oscuro correspondientes a <span class="math inline">\(LQ≈1\)</span> indicando que el sector sigue la densidad económica general sin generar especialización propia — resultado coherente con el signo negativo de <span class="math inline">\(\hat{\gamma}_{MS}\)</span>. En la franja central-norte y periferia oriental emergen nodos de especialización moderada-alta (<span class="math inline">\(2≤LQ≤5\)</span>), coincidentes con corredores de expansión urbana donde la demanda endógena por insumos de construcción es estructuralmente mayor. Los polígonos amarillo-naranja dispersos en la periferia corresponden con alta probabilidad a los casos de LQ artefactual ya discutidos.</p>
<p>Los índices anteriores comparten una limitación común: operan sobre particiones discretas del espacio en barrios, lo que introduce dependencia de los resultados respecto a cómo se definen las fronteras geográficas (<em>MAUP</em>). Las funciones <span class="math inline">\(\hat{K}_d\)</span> y <span class="math inline">\(M\)</span> resuelven este problema estimando aglomeración sobre el espacio continuo, evaluando directamente las distancias entre establecimientos.</p>
</section>
<section id="estime-las-funciones-hatk_d-de-duranton-y-overman-2005-y-m-de-marcon-y-puech-2010.-interprete-los-resultados-en-términos-de-la-localización-de-las-mayores-densidades-y-de-la-distancia-a-la-que-se-encuentran-las-empresas." class="level1">
<h1>4. Estime las funciones <span class="math inline">\(\hat{K}_d\)</span> de Duranton y Overman (2005) y <span class="math inline">\(M\)</span> de Marcon y Puech (2010). Interprete los resultados en términos de la localización de las mayores densidades y de la distancia a la que se encuentran las empresas.</h1>
<section id="a-función-hatk_d-de-duranton-y-overman-2005" class="level3">
<h3 class="anchored" data-anchor-id="a-función-hatk_d-de-duranton-y-overman-2005">a) Función <span class="math inline">\(\hat{K}_d\)</span> de Duranton y Overman (2005)</h3>
<p>La función <span class="math inline">\(\hat{K}_d\)</span> estima la densidad de distancias bilaterales entre establecimientos del sector, evaluando si la distribución empírica de esas distancias difiere significativamente de una distribución de referencia aleatoria (Duranton y Overman, 2005). Formalmente:</p>
<p><span class="math display">\[\hat{K}_d(d) = \frac{1}{n(n-1)} \sum_{i=1}^{n} \sum_{j \neq i} \frac{1}{h}\phi\left(\frac{d - d_{ij}}{h}\right)\]</span></p>
<p>donde <span class="math inline">\(d_{ij}\)</span> es la distancia euclidiana entre los establecimientos <span class="math inline">\(i\)</span> y <span class="math inline">\(j\)</span>, <span class="math inline">\(\phi(\cdot)\)</span> es el kernel gaussiano estándar con ancho de banda <span class="math inline">\(h\)</span>, y <span class="math inline">\(n\)</span> es el número total de establecimientos del sector. El contrafactual se construye mediante remuestreo aleatorio de las localizaciones observadas en la economía general, generando bandas de confianza al <span class="math inline">\(5\%\)</span> por simulación de Monte Carlo. Se concluye:</p>
<ul>
<li><strong>Aglomeración</strong> a distancia <span class="math inline">\(d\)</span> si <span class="math inline">\(\hat{K}_d(d) &gt;\)</span> banda superior</li>
<li><strong>Dispersión</strong> a distancia <span class="math inline">\(d\)</span> si <span class="math inline">\(\hat{K}_d(d) &lt;\)</span> banda inferior</li>
<li><strong>Aleatoriedad</strong> si <span class="math inline">\(\hat{K}_d(d)\)</span> se encuentra dentro de las bandas</li>
</ul>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 1. Ventana espacial continua desde el shapefile ──────────────────────────</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>window <span class="ot">&lt;-</span> <span class="fu">as.owin</span>(<span class="fu">st_union</span>(barriosCali) <span class="sc">|&gt;</span> <span class="fu">st_transform</span>(crs))</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 2. Coordenadas de todos los puntos de la economía general ────────────────</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>coords_total <span class="ot">&lt;-</span> data_total <span class="sc">|&gt;</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(x), <span class="sc">!</span><span class="fu">is.na</span>(y)) <span class="sc">|&gt;</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>(<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"x"</span>, <span class="st">"y"</span>), <span class="at">crs =</span> crs) <span class="sc">|&gt;</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_coordinates</span>()             <span class="co"># Extrae matriz de coordenadas X, Y</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 3. Marks: etiqueta de tipo (Sector vs. Economía) y peso uniforme ─────────</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>marks_all <span class="ot">&lt;-</span> data_total <span class="sc">|&gt;</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(x), <span class="sc">!</span><span class="fu">is.na</span>(y)) <span class="sc">|&gt;</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">PointType   =</span> <span class="fu">ifelse</span>(ciiu_4 <span class="sc">==</span> <span class="st">"2030"</span>, <span class="st">"Sector"</span>, <span class="st">"Economia"</span>),</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">PointWeight =</span> <span class="dv">1</span>             <span class="co"># Peso uniforme: todas las empresas pesan igual</span></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(PointType, PointWeight)</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 4. Construcción del objeto wmppp para dbmss ──────────────────────────────</span></span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a><span class="co"># wmppp: Weighted Marked Planar Point Process — proceso de puntos marcados</span></span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>wmppp_all <span class="ot">&lt;-</span> <span class="fu">wmppp</span>(</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">X           =</span> coords_total[, <span class="dv">1</span>],</span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">Y           =</span> coords_total[, <span class="dv">2</span>],</span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">PointType   =</span> marks_all<span class="sc">$</span>PointType,</span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">PointWeight =</span> marks_all<span class="sc">$</span>PointWeight</span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">window =</span> window</span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-30"><a href="#cb27-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-31"><a href="#cb27-31" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 5. Ancho de banda h por regla de Silverman ───────────────────────────────</span></span>
<span id="cb27-32"><a href="#cb27-32" aria-hidden="true" tabindex="-1"></a><span class="co"># 5.1 Coordenadas del sector para calcular distancias bilaterales</span></span>
<span id="cb27-33"><a href="#cb27-33" aria-hidden="true" tabindex="-1"></a>coords_sector <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span></span>
<span id="cb27-34"><a href="#cb27-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(x), <span class="sc">!</span><span class="fu">is.na</span>(y)) <span class="sc">|&gt;</span></span>
<span id="cb27-35"><a href="#cb27-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(x, y)</span>
<span id="cb27-36"><a href="#cb27-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-37"><a href="#cb27-37" aria-hidden="true" tabindex="-1"></a><span class="co"># 5.2 Matriz de distancias bilaterales entre todos los pares del sector</span></span>
<span id="cb27-38"><a href="#cb27-38" aria-hidden="true" tabindex="-1"></a>dist_sector <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">dist</span>(coords_sector))</span>
<span id="cb27-39"><a href="#cb27-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-40"><a href="#cb27-40" aria-hidden="true" tabindex="-1"></a><span class="co"># 5.3 h óptimo por Silverman: minimiza MISE bajo distribución gaussiana</span></span>
<span id="cb27-41"><a href="#cb27-41" aria-hidden="true" tabindex="-1"></a>h_silverman <span class="ot">&lt;-</span> <span class="fu">bw.nrd0</span>(dist_sector)</span>
<span id="cb27-42"><a href="#cb27-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-43"><a href="#cb27-43" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Ancho de banda h (Silverman):"</span>, <span class="fu">round</span>(h_silverman, <span class="dv">1</span>), <span class="st">"metros</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Ancho de banda h (Silverman): 268.3 metros</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Radio efectivo de influencia (3h):"</span>, <span class="fu">round</span>(<span class="dv">3</span> <span class="sc">*</span> h_silverman, <span class="dv">1</span>), <span class="st">"metros</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Radio efectivo de influencia (3h): 804.8 metros</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 6. Moda de distancias bilaterales — sector y economía general ────────────</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 6.1 Moda del sector: distancia más frecuente entre pares de empresas del sector</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>dens_sec <span class="ot">&lt;-</span> <span class="fu">density</span>(dist_sector, <span class="at">from =</span> <span class="dv">0</span>)    <span class="co"># from=0 evita masa negativa</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>moda_sec <span class="ot">&lt;-</span> dens_sec<span class="sc">$</span>x[<span class="fu">which.max</span>(dens_sec<span class="sc">$</span>y)]</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Moda sector:"</span>, <span class="fu">round</span>(moda_sec, <span class="dv">1</span>), <span class="st">"metros</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Moda sector: 2816.4 metros</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 6.2 Moda de la economía general (muestra aleatoria para eficiencia computacional)</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>coords_eco <span class="ot">&lt;-</span> data_total <span class="sc">|&gt;</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(x), <span class="sc">!</span><span class="fu">is.na</span>(y)) <span class="sc">|&gt;</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">500</span>) <span class="sc">|&gt;</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(x, y)</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>dist_eco <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">dist</span>(coords_eco))</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>dens_eco <span class="ot">&lt;-</span> <span class="fu">density</span>(dist_eco, <span class="at">from =</span> <span class="dv">0</span>)</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>moda_eco <span class="ot">&lt;-</span> dens_eco<span class="sc">$</span>x[<span class="fu">which.max</span>(dens_eco<span class="sc">$</span>y)]</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Moda economía general:"</span>, <span class="fu">round</span>(moda_eco, <span class="dv">1</span>), <span class="st">"metros</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Moda economía general: 3492.3 metros</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 7. Estimación de K_d con bandas de confianza por Monte Carlo ─────────────</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>r_seq <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">3000</span>, <span class="at">by =</span> <span class="dv">50</span>)    <span class="co"># Secuencia de distancias a evaluar (0 a 3km)</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>Kd_result <span class="ot">&lt;-</span> dbmss<span class="sc">::</span><span class="fu">KdEnvelope</span>(</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">X                   =</span> wmppp_all,</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">ReferenceType       =</span> <span class="st">"Sector"</span>,</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">r                   =</span> r_seq,</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">NumberOfSimulations =</span> <span class="dv">999</span>,       <span class="co"># 999 réplicas de Monte Carlo</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Alpha               =</span> <span class="fl">0.05</span>       <span class="co"># Bandas de confianza al 95%</span></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 8. Visualización de K_d con información del ancho de banda ───────────────</span></span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(Kd_result) <span class="sc">+</span></span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">title    =</span> <span class="fu">expression</span>(<span class="st">"Función "</span> <span class="sc">*</span> <span class="fu">hat</span>(K)[d] <span class="sc">*</span> <span class="st">" — Duranton &amp; Overman (2005)"</span>),</span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">paste0</span>(<span class="st">"Sector CIIU 2030 — Cali  |  "</span>,</span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"h = "</span>, <span class="fu">round</span>(h_silverman, <span class="dv">0</span>), <span class="st">" m  |  "</span>,</span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Radio efectivo = "</span>, <span class="fu">round</span>(<span class="dv">3</span> <span class="sc">*</span> h_silverman, <span class="dv">0</span>), <span class="st">" m"</span>),</span>
<span id="cb35-20"><a href="#cb35-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">x        =</span> <span class="st">"Distancia (metros)"</span>,</span>
<span id="cb35-21"><a href="#cb35-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">y        =</span> <span class="fu">expression</span>(<span class="fu">hat</span>(K)[d](d)),</span>
<span id="cb35-22"><a href="#cb35-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption  =</span> <span class="st">"Bandas de confianza al 95% por simulación de Monte Carlo (999 réplicas). h por regla de Silverman."</span></span>
<span id="cb35-23"><a href="#cb35-23" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb35-24"><a href="#cb35-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb35-25"><a href="#cb35-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb35-26"><a href="#cb35-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title    =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb35-27"><a href="#cb35-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>, <span class="at">color =</span> <span class="st">"grey40"</span>),</span>
<span id="cb35-28"><a href="#cb35-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption  =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>,  <span class="at">color =</span> <span class="st">"grey50"</span>),</span>
<span id="cb35-29"><a href="#cb35-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title    =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>),</span>
<span id="cb35-30"><a href="#cb35-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text     =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>),</span>
<span id="cb35-31"><a href="#cb35-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.text   =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>),</span>
<span id="cb35-32"><a href="#cb35-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.margin   =</span> <span class="fu">margin</span>(<span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">10</span>, <span class="dv">10</span>)</span>
<span id="cb35-33"><a href="#cb35-33" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="taller_3_revised_files/figure-html/Kd_Duranton_Overman-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>La función <span class="math inline">\(\hat{K}_d\)</span> ofrece tres lecturas complementarias sobre la estructura espacial del sector. Primero, las distancias entre pares de empresas del sector tienen una moda de <span class="math inline">\(2.816\)</span> metros, indicando que la mayor densidad probabilística de encontrar dos empresas del sector se da a esa escala — equivalente a una distancia de caminata urbana extendida. Que el sector no exhiba una moda a distancias muy cortas sugiere que no existe un incentivo predominante de co-localización inmediata, lo que es consistente con la naturaleza del bien que comercia: insumos intermedios cuya demanda está distribuida a lo largo de la ciudad. Segundo, la moda de distancias del sector (<span class="math inline">\(2.816\)</span> m) es menor que la de la economía general (<span class="math inline">\(3.492\)</span> m), lo que indica que existe un proceso de aglomeración intrasectorial relativo — las empresas del sector están más próximas entre sí que el promedio de la economía, posiblemente por la cobertura geográfica acotada del sector frente a la amplitud de la economía general. Tercero, el ancho de banda óptimo <span class="math inline">\(h = 268\)</span> metros determina el radio efectivo de influencia dentro del cual la co-localización entre establecimientos es estadísticamente informativa: pares de empresas separados por más de <span class="math inline">\(3h \approx 804\)</span> metros tienen un peso marginal en la estimación de densidad, sugiriendo que las eventuales externalidades del sector operan a escala de caminata urbana.</p>
</section>
<section id="b-función-m-de-marcon-y-puech-2010" class="level3">
<h3 class="anchored" data-anchor-id="b-función-m-de-marcon-y-puech-2010">b) Función <span class="math inline">\(M\)</span> de Marcon y Puech (2010)</h3>
<p>La función <span class="math inline">\(M\)</span> es una extensión relativa de <span class="math inline">\(\hat{K}_d\)</span> que corrige el sesgo por heterogeneidad espacial de la economía de referencia (Marcon y Puech, 2010). Al comparar la proporción de vecinos del mismo sector contra la proporción de vecinos de la economía general dentro de cada radio <span class="math inline">\(r\)</span>, controla automáticamente por la densidad económica local en cada punto del espacio. Formalmente:</p>
<p><span class="math display">\[M(r) = \frac{\sum_{i} \sum_{j \neq i} \mathbf{1}[d_{ij} \leq r] \cdot \mathbf{1}[j \in \text{Sector}]}{\sum_{i} \sum_{j \neq i} \mathbf{1}[d_{ij} \leq r]} \cdot \frac{n}{n_s}\]</span></p>
<p>donde <span class="math inline">\(n_s\)</span> es el número de establecimientos del sector y <span class="math inline">\(n\)</span> el total de establecimientos de la economía. La normalización <span class="math inline">\(n/n_s\)</span> garantiza que bajo distribución aleatoria <span class="math inline">\(M(r) = 1\)</span> para todo <span class="math inline">\(r\)</span>:</p>
<ul>
<li><span class="math inline">\(M(r) &gt; 1\)</span> — <strong>aglomeración</strong>: vecindario del sector más denso sectorialmente que la economía de referencia</li>
<li><span class="math inline">\(M(r) &lt; 1\)</span> — <strong>dispersión</strong>: vecindario menos denso que lo esperado</li>
<li><span class="math inline">\(M(r) = 1\)</span> — <strong>aleatoriedad</strong>: composición del vecindario indistinguible de la economía general</li>
</ul>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 1. Estimación de la función M con bandas de confianza ────────────────────</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Reutiliza wmppp_all y r_seq construidos en el bloque anterior</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>M_result <span class="ot">&lt;-</span> dbmss<span class="sc">::</span><span class="fu">MEnvelope</span>(</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">X                   =</span> wmppp_all,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ReferenceType       =</span> <span class="st">"Sector"</span>,    <span class="co"># Empresa focal: del sector</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">NeighborType        =</span> <span class="st">"Sector"</span>,    <span class="co"># Vecinos evaluados: del mismo sector</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">r                   =</span> r_seq,</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">NumberOfSimulations =</span> <span class="dv">999</span>,</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Alpha               =</span> <span class="fl">0.05</span></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a><span class="co"># ─── 2. Visualización de M con línea de referencia aleatoria ──────────────────</span></span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(M_result) <span class="sc">+</span></span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">1</span>,</span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>             <span class="at">linetype   =</span> <span class="st">"dashed"</span>,</span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>             <span class="at">color      =</span> <span class="st">"red"</span>,</span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>             <span class="at">linewidth  =</span> <span class="fl">0.5</span>) <span class="sc">+</span>    <span class="co"># M = 1: referencia bajo aleatoriedad</span></span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">title    =</span> <span class="st">"Función M — Marcon &amp; Puech (2010)"</span>,</span>
<span id="cb36-20"><a href="#cb36-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Sector CIIU 2030 — Cali"</span>,</span>
<span id="cb36-21"><a href="#cb36-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">x        =</span> <span class="st">"Distancia (metros)"</span>,</span>
<span id="cb36-22"><a href="#cb36-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">y        =</span> <span class="st">"M(r)"</span>,</span>
<span id="cb36-23"><a href="#cb36-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption  =</span> <span class="st">"Línea roja: M = 1 (referencia aleatoria). Bandas al 95% por Monte Carlo."</span></span>
<span id="cb36-24"><a href="#cb36-24" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb36-25"><a href="#cb36-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb36-26"><a href="#cb36-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb36-27"><a href="#cb36-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title    =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb36-28"><a href="#cb36-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>, <span class="at">color =</span> <span class="st">"grey40"</span>),</span>
<span id="cb36-29"><a href="#cb36-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption  =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>,  <span class="at">color =</span> <span class="st">"grey50"</span>),</span>
<span id="cb36-30"><a href="#cb36-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title    =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>),</span>
<span id="cb36-31"><a href="#cb36-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text     =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>),</span>
<span id="cb36-32"><a href="#cb36-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.margin   =</span> <span class="fu">margin</span>(<span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">10</span>, <span class="dv">10</span>)</span>
<span id="cb36-33"><a href="#cb36-33" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="taller_3_revised_files/figure-html/M_Marcon_Puech-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>La función <span class="math inline">\(M\)</span> complementa y refina el diagnóstico obtenido con <span class="math inline">\(\hat{K}_d\)</span>. Los resultados muestran que <span class="math inline">\(M(r) &gt; 1\)</span> para distancias cortas, confirmando que en ese rango una empresa del sector tiene en su vecindario una proporción de establecimientos del mismo sector significativamente mayor a la que predice la composición de la economía general de Cali — resultado robusto porque, a diferencia del <span class="math inline">\(LQ_i\)</span>, no depende de la partición en barrios ni de la masa económica de cada unidad espacial. La magnitud de <span class="math inline">\(M(r)\)</span> en ese umbral puede interpretarse directamente: un valor de, por ejemplo, <span class="math inline">\(M(r) = 2\)</span> indicaría que una empresa del sector encuentra el doble de vecinos del mismo tipo que los esperados bajo localización aleatoria, lo que constituye evidencia de externalidades de aglomeración operando a esa escala. En conjunto, <span class="math inline">\(\hat{K}_d\)</span> y <span class="math inline">\(M\)</span> ofrecen unacaracterización espacialmente continua y libre del <em>MAUP</em> que es consistente con todos los indicadores estimados previamente.</p>
<p>En consecuencia al analisis previo, el sector de fabricación de insumos intermedios para construcción en Cali exhibe aglomeración local de corto alcance en la zona central de la ciudad, impulsada por encadenamientos productivos y externalidades informacionales, Asimismo, posee una probabilidad mayor de encontrar dos pares de empresas en una menor distancia relativa a la economía general. Por otro lado, se encuentra que las decisiones de co-localización están incentivadas a sectores con una mayor participación economica del sector, sin embargo, no existe evidencia suficiente para una estructura de especialización sectorial propia en un barrio especifico diferente a la distribucion de especialización productiva dada en la ciudad de Cali.</p>
</section>
<section id="referencias" class="level2">
<h2 class="anchored" data-anchor-id="referencias">Referencias</h2>
<p>Ellison, G., y Glaeser, E. L. (1997). Geographic concentration in U.S. manufacturing industries: A dartboard approach. <em>Journal of Political Economy</em>, <em>105</em>(5), 889–927. https://doi.org/10.1086/262098</p>
<p>Herfindahl, O. C. (1950). <em>Concentration in the steel industry</em> [Doctoral dissertation, Columbia University].</p>
<p>Hirschman, A. O. (1945). <em>National power and the structure of foreign trade</em>. University of California Press.</p>
<p>Marcon, E., y Puech, F. (2010). Measures of the geographic concentration of industries: Improving distance-based methods. <em>Journal of Economic Geography</em>, <em>10</em>(5), 745–762. https://doi.org/10.1093/jeg/lbp056</p>
<p>Maurel, F., y Sédillot, B. (1999). A measure of the geographic concentration in French manufacturing industries. <em>Regional Science and Urban Economics</em>, <em>29</em>(5), 575–604. https://doi.org/10.1016/S0166-0462(99)00020-4</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>